new_password checks to see if passwords file exists.

diff --git a/new_password b/new_password
--- a/new_password
+++ b/new_password
@@ -3,6 +3,12 @@ tmp="/run/shm/$tmp"
 pwfile="$HOME/private/passwords.txt.gpg"
 key="92F6D2F8"
 
+if [ ! [ -a "$pwfile" ] ]
+then
+echo "Passwords file not found."
+exit 1
+fi
+
 gpg2 -o "$tmp" -d "$pwfile"
 
 echo "Creating new entry in personal passwords file."
